stages:
  - test
  - build
  - push
  - deploy

test_gateway:
  stage: test
  image: openjdk:8-jdk-alpine
  script:
    - ./mvnw test -pl backend/Api-Gateway/pom.xml
  only:
    changes:
      - backend/Api-Gateway/**/*

test_appliance_service:
  stage: test
  image: openjdk:8-jdk-alpine
  script:
    - ./mvnw test -pl backend/Api-Gateway/pom.xml
  only:
    changes:
      - backend/Appliance-Service/**/*

test_authorization_service:
  stage: test
  image: openjdk:8-jdk-alpine
  script:
    - ./mvnw test -pl backend/Authorization-Server/pom.xml
  only:
    changes:
      - backend/Authorization-Server/**/*

test_bullitenboard_service:
  stage: test
  image: openjdk:8-jdk-alpine
  script:
    - ./mvnw test -pl backend/Bulletinboard-Service/pom.xml
  only:
    changes:
      - backend/Bulletinboard-Service/**/*


build_gateway:
  stage: build
  image: openjdk:8-jdk-alpine
  script:
    - ./mvnw spring-boot:build-image -pl backend/Api-Gateway/pom.xml
  only:
    changes:
      - backend/Api-Gateway/**/*

build_appliance_service:
  stage: build
  image: openjdk:8-jdk-alpine
  script:
    - ./mvnw spring-boot:build-image -pl backend/Api-Gateway/pom.xml
  only:
    changes:
      - backend/Appliance-Service/**/*

build_authorization_service:
  stage: build
  image: openjdk:8-jdk-alpine
  script:
    - ./mvnw spring-boot:build-image -pl backend/Authorization-Server/pom.xml
  only:
    changes:
      - backend/Authorization-Server/**/*

build_bullitenboard_service:
  stage: build
  image: openjdk:8-jdk-alpine
  script:
    - ./mvnw spring-boot:build-image -pl backend/Bulletinboard-Service/pom.xml
  only:
    changes:
      - backend/Bulletinboard-Service/**/*

build_spring_boot_admin:
  stage: build
  image: openjdk:8-jdk-alpine
  script:
    - ./mvnw spring-boot:build-image -pl backend/Spring-Boot-Admin/pom.xml
  only:
    changes:
      - backend/Spring-Boot-Admin/**/*

push_stage:
  stage: push
  image: alpine

deploy_stage:
  stage: deploy
  image: alpine