#%RAML 1.0 DataType

      properties:
        id:
          type: integer
        serial_number:
          type: integer
        student: !include Student.raml
        appliance: !include Appliance.raml
        creation_date:
          type: datetime
        selected_end_date:
          type: datetime   
        actual_end_date:
          type: datetime             
        rent_amount:
          type: number
          format: double
        number_of_appliances:
          type: integer
        status:
          type: string
          enum: 
            - RENTED
            - TERMINATED