#%RAML 1.0 DataType

      properties:
        id:
          type: integer
        user: !include User.raml
        room_number:
          type: integer
        semester:
          type: string
        join_date:
          type: string