#%RAML 1.0 Trait

body:
  application/json:
    type: <<type-name>>
responses:
  '401': 
    description: Unauthorized. Please check your credentials
  '403':
    description: Forbidden. Sorry, you can not access  
    